### ISSUE TITLE
Delete wish list by user id and model id

### ISSUE THREAD

**Issue by ArtMin96** [lamalamaNL/laravel-wishlist#7]
How to check if the user already has a specific wishlist. And if found remove that?

**Comment by lamalamaMark** [comment]
Do you mean a specific wishlist or a specific item on a wishlist?

**Comment by ArtMin96** [comment]
> Do you mean a specific wishlist or a specific item on a wishlist?

I have already finished adding the wish list. After the second click of the user, I have to check if he already has this wish list, then it will be deleted

**Comment by ArtMin96** [comment]
Need to check specific user_id and model_id

**Comment by lamalamaMark** [comment]
Do you want to delete a whole wishlist or only a specific item on the wishlist?

**Comment by ArtMin96** [comment]
Specific item. I have to check if user already has this wish list

**Comment by lamalamaMark** [comment]
It stays unclear to me:- you can have multiple wishlists, do you want to check if a specific wishlist has items?
- you can put items on a wishlist, do you want to check if a specific item is on a specific wishlist?




Mark de Vries


06 418 43 246
mark@lamalama.nl
lamalama.nl



Nieuwe Teertuinen 23

1013 LV Amsterdam

020 6 220 440

--- original message ---
On 25 October 2020, 11:20 AM CET notifications@github.com wrote:



Specific item. I have to check if user already has this wish list

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by lamalamaMark** [comment]
It stays unclear to me:
- you can have multiple wishlists, do you want to check if a specific wishlist has items?
- you can put items on a wishlist, do you want to check if a specific item is on a specific wishlist?

**Comment by ArtMin96** [comment]
Before adding I need to check if user already has selected item in the wish list. Like Wishlist::where('user_id', $user->id)->where('model_id', '$request->id')->first(); and check if wish list not exist than add.

```
public function addWishlist(Request $request) {
    if (!empty($request->post('id'))) {
        $user = User::find(\Auth::user()->id);
        $product = Product::find($request->post('id'));
        $wishlists = $user->wishlist();

        if ($user->wish($product)) {
            return response()->json(['status' => true, 'title' => 'Success', 'message' => $product->title.' added to your wishlist!']);
        } else {
            return response()->json(['status' => false, 'title' => 'Error', 'message' => 'Please try again!']);
        }
    } else {
        return response()->json(['status' => false, 'title' => 'Error', 'message' => 'Please try again!']);
    }
}
```
